eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080


spring:
#   main:
#     web-application-type: reactive
  application:
    name: api-gateway
#   cloud:
#     compatibility-verifier:
#       enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: registration-service
          uri: http://localhost:8087
          predicates:
            - Path=/registration-service/**
          filters:
            - RewritePath=/registration-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:9088
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: http://localhost:8081
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}

        - id: interviewer-service
          uri: http://localhost:8086
          predicates:
            - Path=/interviewer-service/**
          filters:
            - RewritePath=/interviewer-service(?<segment>/?.*), $\{segment}

        - id: TAG-team-service
          uri: http://localhost:8094
          predicates:
            - Path=/TAG-team-service/**
          filters:
            - RewritePath=/TAG-team-service(?<segment>/?.*), $\{segment}
